### ISSUE TITLE
La versión en proyectos.md tiene que corresponder a un tag en este repositorio

### ISSUE THREAD

**Issue by JJ** [BotAnalyzer/MessagesAnalyzer#15]
El error en test actual se debe a esto. Trata de bajarse el tag que indicáis, y no lo encuentra porque no existe.

**Comment by aviola** [comment]
Generated tag v0.0.1

**Comment by JJ** [comment]
Tenéis que actualizar el PR (editando el fichero) para que vuelva a pasar los tests.
